Repository fankiat/sopht-mpi, pull requests merged in 2022-09, with the labels that each got.

#5 mpi ghost communicator 3d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py
  sopht_mpi/utils/__init__.py
  sopht_mpi/utils/mpi_utils_2d.py
  sopht_mpi/utils/mpi_utils_3d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
  tests/test_utils/test_mpi_utils_2d.py
  tests/test_utils/test_mpi_utils_3d.py
Labels: enhancement

#7 mpi io communicator 3d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py
  sopht_mpi/utils/__init__.py
  sopht_mpi/utils/mpi_utils_2d.py
  sopht_mpi/utils/mpi_utils_3d.py
  tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
  tests/test_utils/test_mpi_utils_2d.py
  tests/test_utils/test_mpi_utils_3d.py
Labels: enhancement

#10 refactor: rename fieldIO -> field
  .github/workflows/main.yml
  sopht_mpi/utils/__init__.py
  sopht_mpi/utils/mpi_utils_2d.py
  sopht_mpi/utils/mpi_utils_3d.py
  tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
  tests/test_utils/test_mpi_utils_2d.py
  tests/test_utils/test_mpi_utils_3d.py
Labels: refactor

#11 fix: master --> main in CI push checks
  .github/workflows/main.yml
Labels: bug

#13 Storing and accessing kernel_support in kernels
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py
  sopht_mpi/utils/__init__.py
  sopht_mpi/utils/mpi_utils.py
  tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
Labels: enhancement

#15 mpi diffusion timestep 2d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_flux_mpi_2d.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/diffusion_timestep_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py
Labels: enhancement

#24 mpi outplane field curl 2d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/outplane_field_curl_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py
Labels: enhancement

#26 refactor: test problem size
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py
  tests/test_utils/test_mpi_utils_2d.py
  tests/test_utils/test_mpi_utils_3d.py
Labels: refactor

#27 mpi brinkmann penalise 2d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/brinkmann_penalise_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py
Labels: enhancement

#29 refactor: rename field_io_* -> field_*
  tests/test_numeric/test_eulerian_grid_ops/test_poisson_solver_2d/test_fft_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_flux_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_advection_timestep_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_flux_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_diffusion_timestep_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_outplane_field_curl_mpi_2d.py
  tests/test_utils/test_mpi_utils_2d.py
  tests/test_utils/test_mpi_utils_3d.py
Labels: refactor

#35 mpi char func from level set 2d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/char_func_from_level_set_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py
Labels: enhancement, prio:high

#33 mpi update vorticity from velocity forcing 2d
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/update_vorticity_from_velocity_forcing_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_update_vorticity_from_velocity_forcing_mpi_2d.py
Labels: enhancement, prio:high

#40 fix : zero kernel support index fix for comparison
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_brinkmann_penalise_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_char_func_from_level_set_mpi_2d.py
Labels: bug, prio:high

#38 mpi penalise field boundary 2d
  poetry.lock
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/__init__.py
  sopht_mpi/numeric/eulerian_grid_ops/stencil_ops_2d/penalise_field_boundary_mpi_2d.py
  tests/test_numeric/test_eulerian_grid_ops/test_stencil_ops_2d/test_penalise_field_boundary_mpi_2d.py
Labels: enhancement, prio:high

#41 update: sopht backend with vorticity stretching ssprk3 timestep
  poetry.lock
Labels: enhancement, prio:high
